name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: "1.5.8-0"
          environment-name: smsdpro      
          create-args: >-               
            python=3.11
            rdkit=2025.03.6
            numpy
            pillow
            matplotlib
            pytest
            pip
          condarc: |
            channels:
              - conda-forge
            channel_priority: strict

      - name: Install package
        shell: bash -l {0}
        run: |
          pip install --no-deps -e .

      - name: Unit tests (fast)
        shell: bash -l {0}
        run: |
          pytest -q

      - name: Run benchmark suite
        shell: bash -l {0}
        run: |
          python scripts/bench.py --limit-png 20
        continue-on-error: true

      - name: Upload artefacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: smsdpro-artifacts
          path: test_output/
